### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by copumpkin** [brturn/feeds-and-speeds#2]
Hi, love the project but I was wondering what the license on this code is. I’m a hobbyist and have no plans to use it commercially but if I extend or make changes to it I don’t want to run afoul of a license. I see the HTML says all rights reserved which I think would forbid anything much but it’s unclear what the scope of that was intended to be.

Can you help clarify? Thanks!

**Comment by brturn** [comment]
Hello - the code is marked GPL v3 in the source header.

Thanks for your interest!
